manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0 # Pinned release. Move to v0.4 once tagged (board becomes nice_nano//zmk).
      import: app/west.yml
  self:
    path: config
